# Copyright 2026 The Project Contributors
# SPDX-License-Identifier: MIT

[tools]
python = "3.14"
uv = "0.11.10"
duckdb = "1.5.2"
hk = "latest"
pkl = "latest"
"github:google/addlicense" = "latest"
actionlint = "latest"
taplo = "latest"
shellcheck = "latest"
shfmt = "latest"

[env]
HK_MISE = 1
LICENSE_TYPE = "mit"
LICENSE_HOLDER = "The Project Contributors"

[settings]
experimental = true
python.uv_venv_auto = "create|source"

[task_config]
includes = ["tasks"]
